Fragment large SMP messages over mutiple writes
LairdCP/sdk-nrf pull request #3
Opened 2022-08-17 19:41 UTC by randyscott

This change is to the DFU SMP "client." Instead of limiting an SMP message to whatever fits into a single write, allow the SMP message to span multiple writes. This fragmentation (and reassembly) is already supported in the standard SMP "server" (that runs on the BLE peripheral) and other parts of this same DFU SMP "client."

2022-08-17 19:53 UTC, rerickson1 requested changes

2022-08-17 19:53 UTC, rerickson1 commented on subsys/bluetooth/services/dfu_smp.c
> +		ret = bt_gatt_write_without_response(dfu_smp->conn,
why - 3? Should this be a define and have more detailed comments?

2022-08-17 20:23 UTC, ahedin25 approved these changes, later dismissed

2022-08-17 21:04 UTC, rerickson1 commented
squash and force push to cleanup the fixup commit.

2022-08-18 16:01 UTC, rerickson1 approved these changes

2022-08-18 16:01 UTC, merged